baseURL = 'https://pooyapm.github.io/'
languageCode = 'en-us'
title = "Pooya Mozzemi' Blog"
theme = 'hugo-PaperMod'
relativeURLs = true
[params]
env = "production"
[params.assets]
disableFingerprinting = true

[[menu.main]]
identifier = "Technology"
name = "Technology"
url = "/Technology/"
weight = 10

[[menu.main]]
identifier = "Soft Skills"
name = "Soft Skills"
url = "/Soft Skills/"
weight = 20

[[menu.main]]
identifier = "Business Management"
name = "Business Management"
url = "/Business Management/"
weight = 30

[[menu.main]]
identifier = "Product Management"
name = "Product Management"
url = "/Product Management/"
weight = 40

[[menu.main]]
identifier = "Economy"
name = "Economy"
url = "/Economy/"
weight = 50

[[menu.main]]
identifier = "About Me"
name = "About"
url = "/About/"
weight = 60