baseURL = '/'
languageCode = 'en-us'
title = "Pooya Mozzemi' Blog"
theme = 'hugo-PaperMod'
relativeURLs = true
enableEmoji = true

[markup.goldmark.renderer]
unsafe= true
[params]
env = "production"
disableThemeToggle = true
defaultTheme = 'light'

[params.homeInfoParams]
title = "Welcome to my blog :wave:"
content = "This is Pooya. Here I write about the frameworks, concepts and principles I have developed over the years. I also document my new learnings and findings and solutions to problems which may be your problems too. I hope you find it helpful."

[[params.socialIcons]]
name = "Paypal"
url = "https://paypal.me/pooyapm"

[[params.socialIcons]]
name = "Pf"
url = "twitter.com"

[params.assets]
disableFingerprinting = true

[[menu.main]]
identifier = "Technology"
name = "Technology"
url = "categories/technology/"
weight = 10

[[menu.main]]
identifier = "Soft Skills"
name = "Soft Skills"
url = "categories/soft-skills/"
weight = 20

[[menu.main]]
identifier = "Business Management"
name = "Business Management"
url = "categories/business-management/"
weight = 30

[[menu.main]]
identifier = "Product Management"
name = "Product Management"
url = "categories/product-management/"
weight = 40

[[menu.main]]
identifier = "About Me"
name = "About Me"
url = "about-me/about-me/"
weight = 60