baseURL = '/'
languageCode = 'en-us'
title = "Pooya Mozzemi' Blog"
theme = 'hugo-PaperMod'
relativeURLs = true
[markup.goldmark.renderer]
unsafe= true
[params]
env = "production"
disableThemeToggle = true
defaultTheme = 'light'
[params.assets]
disableFingerprinting = true

[[menu.main]]
identifier = "Technology"
name = "Technology"
url = "./technology/"
weight = 10

[[menu.main]]
identifier = "Soft Skills"
name = "Soft Skills"
url = "categories/soft-skills/"
weight = 20

[[menu.main]]
identifier = "Business Management"
name = "Business Management"
url = "./business-management/"
weight = 30

[[menu.main]]
identifier = "Product Management"
name = "Product Management"
url = "./product-management/"
weight = 40

[[menu.main]]
identifier = "About Me"
name = "About Me"
url = "./about-me/"
weight = 60